### ISSUE TITLE
Init source & adding PR template

### ISSUE THREAD

**Issue by moitran** [moitran/git-practice#1]
* Add PR template
```
## Type

- [ ] User Story
- [ ] Technical Story
- [ ] Bugfix

## Description

A few sentences describing the overall goals of the pull request's commits.

## Related PRs

List related PRs against other branches / repos:

- None

## Todos

- [ ] My code follows the style guidelines of this project (e.g.Typescript)
- [ ] I have added tests unit- and end2end tests that prove my code works
- [ ] All dependency change have been merged
```

* add this file `random_tasks.php` with content
```
<?php

$list_person_in_charge = [
    "mai-nguyen",
    "thanh-pham",
    "vo-nguyen",
    "kieu-anh",
    "minh-khue",
    "minh-nguyet",
    "lan-anh",
    "tinh-thanh",
];

shuffle($list_person_in_charge);

echo "\nOutput: \n";
foreach ($list_person_in_charge as $task_number => $person_in_charge) {
    echo sprintf("\t0%s-%s\n", $task_number + 1, $person_in_charge);
}
echo "\n";

```
